# Exported from Render on 2025-08-23T04:35:25Z
services:
  - type: web
    name: realestate-marketplace-backend
    runtime: python
    repo: https://github.com/Akfslgn/realestate-marketplace-backend
    plan: free
    envVars:
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ADMIN_SWATCH
        sync: false
      - key: FLASK_APP
        sync: false
      - key: FLASK_ENV
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    region: virginia
    buildCommand: pip install pipenv && pipenv install --system --deploy && python -c "from app import create_app; from app.extensions import db; app = create_app(); app.app_context().push(); db.create_all(); print('Database tables created successfully')"
    startCommand: gunicorn wsgi:app --workers 3 --timeout 60
    autoDeployTrigger: "on"
version: "1"
